backend:
  name: git-gateway
  branch: main
media_folder: 'www/static/uploads'
local_backend: true
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    fields:
      - { name: Title }