backend: { name: git-gateway, branch: master }
locale: 'es'
media_folder: 'static/images/uploads'
collections:
  - name: files
    label: Configuracion
    editor: { preview: false }
    files:
      - label: Playlists
        name: playlists
        file: _data/playlists.json
        fields:
          - label: Playlists
            name: playlists
            widget: list
            allow_add: true
            fields:
              - { label: Titulo, name: titulo, widget: string }
              - { label: URL, name: url, widget: string }
              - { label: Imagen, name: imagen, widget: image }
      - label: Programación
        name: programacion
        file: _data/programacion.json
        fields:
          - label: Programación
            name: programacion
            widget: list
            allow_add: true
            fields:
              - { label: Titulo, name: titulo, widget: string }
              - { label: Imagen, name: imagen, widget: image }
              - { label: Dia, name: dia, widget: string }
              - { label: Horario, name: hora, widget: string }
              - { label: Tags, name: tags, widget: list }
              - { label: Descripcion, name: descripcion, widget: "markdown" }
              - { label: Musicalizacion, name: musicalizacion, widget: string }
              - { label: Contacto, name: contacto, widget: string }
      - label: Editorial
        name: editorial
        file: _data/editorial.json
        fields:
          - label: Editorial
            name: editorial
            widget: list
            allow_add: true
            fields:
              - { label: Titulo, name: titulo, widget: string }
              - { label: Imagen, name: imagen, widget: image }
              - { label: Precio, name: precio, widget: number }
              - { label: URL, name: url, widget: string }
              - { label: Descripcion, name: descripcion, widget: "markdown" }
              - { label: Autor, name: autor, widget: string }
              - { label: Instagram, name: instagram, widget: string }
